[[mounts]]
  source = 'archetypes'
  target = 'archetypes'

[[mounts]]
  source = 'assets'
  target = 'assets'

[[mounts]]
  source = 'data'
  target = 'data'

[[mounts]]
  source = 'i18n'
  target = 'i18n'

[[mounts]]
  source = 'layouts'
  target = 'layouts'

[[mounts]]
  source = 'static'
  target = 'static'

[[mounts]]
  disableWatch = true
  source = 'hugo_stats.json'
  target = 'assets/notwatching/hugo_stats.json'

[[mounts]]
  source = './node_modules/@fontsource-variable/fira-code/files'
  target = 'static/fonts/fira-code'

[[mounts]]
  source = './node_modules/@fontsource-variable/lora/files'
  target = 'static/fonts/lora'

[[mounts]]
  source = './node_modules/@fontsource-variable/fraunces/files'
  target = 'static/fonts/fraunces'
