name: renovate
on:
  schedule:
    - cron: '30 10 * * 5'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@44f24283a60f64273f1294932f16ba61193cccca # v46.1.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: 'info'
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
